# Generated by Django 4.2.10 on 2024-08-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_contest_submission_leaderboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="additional_testcase_input",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="additional_testcase_output",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="testcase_input",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="testcase_output",
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField()),
                ("output_data", models.TextField()),
                ("is_sample", models.BooleanField(default=False)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="dashboard.problem",
                    ),
                ),
            ],
        ),
    ]
